# Generated by Django 4.2.2 on 2023-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('marque', models.CharField(max_length=255)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('nombre_place', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('longeur', models.IntegerField()),
                ('clim', models.BooleanField(blank=True)),
            ],
        ),
    ]
